package com.example.chessboard.ui

const val InteractiveChessBoardTestTag = "interactive-chess-board"
const val PositionEditorClearBoardTestTag = "position-editor-clear-board"
const val PositionEditorInitialPositionTestTag = "position-editor-initial-position"
const val PositionEditorWhiteShortCastleTestTag = "position-editor-white-short-castle"
const val PositionEditorWhiteLongCastleTestTag = "position-editor-white-long-castle"
const val PositionEditorBlackShortCastleTestTag = "position-editor-black-short-castle"
const val PositionEditorBlackLongCastleTestTag = "position-editor-black-long-castle"
const val PositionEditorListTestTag = "position-editor-list"
const val PositionEditorSaveNameFieldTestTag = "position-editor-save-name-field"
const val SavedPositionsContentTestTag = "saved-positions-content"
const val SavedPositionsOpenSelectedTestTag = "saved-positions-open-selected"
const val SavedPositionsPreviousPageTestTag = "saved-positions-previous-page"
const val SavedPositionsNextPageTestTag = "saved-positions-next-page"
const val SavedPositionsSearchActionTestTag = "saved-positions-search-action"
const val SavedPositionsSearchNameFieldTestTag = "saved-positions-search-name-field"
fun savedPositionCardTestTag(positionId: Long): String = "saved-position-card-$positionId"
fun savedPositionCreateButtonTestTag(positionId: Long): String = "saved-position-create-$positionId"
fun savedPositionDeleteButtonTestTag(positionId: Long): String = "saved-position-delete-$positionId"
const val GameEditorScrollContainerTestTag = "game-editor-scroll-container"
const val GameEditorMoveSequenceSectionTestTag = "game-editor-move-sequence-section"
const val EditTrainingListTestTag = "edit-training-list"
const val EditTrainingMoveLegendSectionTestTag = "edit-training-move-legend-section"
const val TrainingEditorGameCardTestTag = "training-editor-game-card"
const val MoveTreeBoxTestTag = "move-tree-box"
const val MoveTreeContentTestTag = "move-tree-content"
const val MoveLegendPreviousTestTag = "move-legend-previous"
const val MoveLegendNextTestTag = "move-legend-next"
const val GameEditorPreviousTestTag = "game-editor-previous"
const val GameEditorNextTestTag = "game-editor-next"
const val BackupRestoreProgressDialogTestTag = "backup-restore-progress-dialog"
const val BackupRestoreCancelTestTag = "backup-restore-cancel"

fun moveChipTestTag(label: String): String = "move-chip-$label"

fun moveTreeRowTestTag(index: Int): String = "move-tree-row-$index"
